name: barizi_nashon_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/svg/


  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/Product Sans Bold Italic.ttf
        - asset: fonts/Product Sans Bold.ttf
          style: italic
        - asset: fonts/Product Sans Italic.ttf 
          weight: 700
        - asset: fonts/Product Sans Regular.ttf 
          weight: 700
